// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/logging.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   string                 `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_proto_logging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_proto_logging_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_proto_logging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_proto_logging_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LogResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartSequence int64                  `protobuf:"varint,1,opt,name=start_sequence,json=startSequence,proto3" json:"start_sequence,omitempty"`
	EndSequence   int64                  `protobuf:"varint,2,opt,name=end_sequence,json=endSequence,proto3" json:"end_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_proto_logging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_logging_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyRequest) GetStartSequence() int64 {
	if x != nil {
		return x.StartSequence
	}
	return 0
}

func (x *VerifyRequest) GetEndSequence() int64 {
	if x != nil {
		return x.EndSequence
	}
	return 0
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_proto_logging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_logging_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_logging_proto protoreflect.FileDescriptor

const file_proto_logging_proto_rawDesc = "" +
	"\n" +
	"\x13proto/logging.proto\x12\x0emerkle.logging\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\n" +
	"LogRequest\x12 \n" +
	"\vapplication\x18\x01 \x01(\tR\vapplication\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12>\n" +
	"\x06fields\x18\x04 \x03(\v2&.merkle.logging.LogRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\vLogResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Y\n" +
	"\rVerifyRequest\x12%\n" +
	"\x0estart_sequence\x18\x01 \x01(\x03R\rstartSequence\x12!\n" +
	"\fend_sequence\x18\x02 \x01(\x03R\vendSequence\"6\n" +
	"\x0eVerifyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x93\x01\n" +
	"\x06Logger\x12@\n" +
	"\x05Write\x12\x1a.merkle.logging.LogRequest\x1a\x1b.merkle.logging.LogResponse\x12G\n" +
	"\x06Verify\x12\x1d.merkle.logging.VerifyRequest\x1a\x1e.merkle.logging.VerifyResponseB\x1fZ\x1dphonax.com/merkle/proto;protob\x06proto3"

var (
	file_proto_logging_proto_rawDescOnce sync.Once
	file_proto_logging_proto_rawDescData []byte
)

func file_proto_logging_proto_rawDescGZIP() []byte {
	file_proto_logging_proto_rawDescOnce.Do(func() {
		file_proto_logging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logging_proto_rawDesc), len(file_proto_logging_proto_rawDesc)))
	})
	return file_proto_logging_proto_rawDescData
}

var file_proto_logging_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_logging_proto_goTypes = []any{
	(*LogRequest)(nil),     // 0: merkle.logging.LogRequest
	(*LogResponse)(nil),    // 1: merkle.logging.LogResponse
	(*VerifyRequest)(nil),  // 2: merkle.logging.VerifyRequest
	(*VerifyResponse)(nil), // 3: merkle.logging.VerifyResponse
	nil,                    // 4: merkle.logging.LogRequest.FieldsEntry
}
var file_proto_logging_proto_depIdxs = []int32{
	4, // 0: merkle.logging.LogRequest.fields:type_name -> merkle.logging.LogRequest.FieldsEntry
	0, // 1: merkle.logging.Logger.Write:input_type -> merkle.logging.LogRequest
	2, // 2: merkle.logging.Logger.Verify:input_type -> merkle.logging.VerifyRequest
	1, // 3: merkle.logging.Logger.Write:output_type -> merkle.logging.LogResponse
	3, // 4: merkle.logging.Logger.Verify:output_type -> merkle.logging.VerifyResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_logging_proto_init() }
func file_proto_logging_proto_init() {
	if File_proto_logging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logging_proto_rawDesc), len(file_proto_logging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logging_proto_goTypes,
		DependencyIndexes: file_proto_logging_proto_depIdxs,
		MessageInfos:      file_proto_logging_proto_msgTypes,
	}.Build()
	File_proto_logging_proto = out.File
	file_proto_logging_proto_goTypes = nil
	file_proto_logging_proto_depIdxs = nil
}
